uk:
  gov:
    notify:
      api:
        key: dummy
        baseUrl: https://api.notifications.service.gov.uk
      email:
        templateVars:
          SAVE_SIGN_OUT:
            signInDivorceUrl: ${NOTIFY_TEMPLATE_SIGN_IN_DIVORCE_URL:https://nfdiv-apply-for-divorce.aat.platform.hmcts.net/}
            signInDissolutionUrl: ${NOTIFY_TEMPLATE_SIGN_IN_DISSOLUTION_URL:https://nfdiv-end-civil-partnership.aat.platform.hmcts.net/}
            divCourtEmail: contactdivorce@justice.gov.uk
            civilPartnershipCourtEmail: endcivilpartnership@justice.gov.uk
        templates:
          english:
            SAVE_SIGN_OUT: '70dd0a1e-047f-4baa-993a-e722db17d8ac'
          welsh:
            SAVE_SIGN_OUT: '70dd0a1e-047f-4baa-993a-e722db17d8ac'

idam:
  s2s-auth:
    url: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    secret: AAAAAAAAAAAAAAAA
    microservice: nfdiv_case_api
  api:
    url: http://localhost:5000
  caseworker:
    username: dummycaseworker@test.com
    password: dummy
  client:
    id: 'divorce'
    secret: BBBBBBBBBBBBBBBB
    redirect_uri: http://localhost:3001/oauth2/callback

s2s-authorised:
  services: ccd_data

fee:
  api:
    baseUrl: http://localhost:4010

s2s:
  stub: true

core_case_data:
  api:
    url: http://localhost:4012

spring:
  main:
    allow-bean-definition-overriding: true

doc_assembly:
  url: ${DOC_ASSEMBLY_URL:http://dg-docassembly-aat.service.core-compute-aat.internal}
