apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "nfdiv-case-api"
  annotations:
    # This must match folder-name/job-name in Jenkins.
    jenkins.io/job-full-name: cft:HMCTS_j_to_z/nfdiv-case-api
    github.com/project-slug: hmcts/nfdiv-case-api
  tags:
    - java
  links:
    - url: https://hmcts-reform.slack.com/app_redirect?channel=no-fault-divorce-tech
      title: "#no-fault-divorce-tech on Slack"
      icon: chat
spec:
  type: service
  lifecycle: production
  owner: dcd_divorce
