package uk.gov.hmcts.divorce.notification;

public enum EmailTemplateName {
    SAVE_SIGN_OUT,
    APPLICATION_SUBMITTED,
    SOL_APPLICANT_APPLICATION_SUBMITTED,
    SOL_APPLICANT_AMENDED_APPLICATION_SUBMITTED,
    SOL_APPLICANT_SOLICITOR_APPLICATION_SUBMITTED,
    SOL_APPLICANT_SOLICITOR_AMENDED_APPLICATION_SUBMITTED;
}
