package uk.gov.hmcts.divorce.notification;

public enum EmailTemplateName {
    SAVE_SIGN_OUT,
    OUTSTANDING_ACTIONS,
    APPLICATION_SUBMITTED,
    JOINT_APPLICANT1_ANSWERS_SENT_FOR_REVIEW,
    JOINT_APPLICANT2_ANSWERS_SENT_FOR_REVIEW,
    JOINT_APPLICANT2_REQUEST_CHANGES,
    JOINT_APPLICANT1_NEED_TO_MAKE_CHANGES,
    SOL_APPLICANT_APPLICATION_SUBMITTED,
    SOL_APPLICANT_AMENDED_APPLICATION_SUBMITTED,
    SOL_APPLICANT_SOLICITOR_APPLICATION_SUBMITTED,
    SOL_APPLICANT_SOLICITOR_AMENDED_APPLICATION_SUBMITTED,
    APPLICANT_SOLICITOR_NOTICE_OF_PROCEEDINGS,
    APPLICANT_NOTICE_OF_PROCEEDINGS,
    RESPONDENT_SOLICITOR_NOTICE_OF_PROCEEDINGS,
    APPLICANT_SOLICITOR_SERVICE,
    GENERAL_EMAIL_PETITIONER,
    GENERAL_EMAIL_PETITIONER_SOLICITOR,
    GENERAL_EMAIL_RESPONDENT,
    GENERAL_EMAIL_RESPONDENT_SOLICITOR,
    GENERAL_EMAIL_OTHER_PARTY;
}
